{% set name = "kitchen" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kitchen-{{ version }}.tar.gz
  sha256: b84cf582f1bd1556b60ebc7370b9d331eb9247b6b070ce89dfe959cba2c0b03c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - kitchen
    - kitchen.collections
    - kitchen
    - kitchen.versioning
    - kitchen.i18n
    - kitchen.iterutils
    - kitchen.collections
    - kitchen.text
    - kitchen.pycompat24
    - kitchen.pycompat24.base64
    - kitchen.pycompat24.sets
    - kitchen.pycompat25
    - kitchen.pycompat25.collections
    - kitchen.pycompat27
    - kitchen.pycompat27.subprocess

  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fedora-infra/kitchen
  summary: Kitchen contains a cornucopia of useful code
  doc_url: https://pythonhosted.org/kitchen/
  license: GPL-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - saibhargav1508
